config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: :new do
    resources :tracks, only: :new
  end

  resources :tracks, except: :new

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :band
  has_many :tracks, dependent: :destroy

  validates_presence_of :name, :band_id
end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :albums, dependent: :destroy
  has_many :tracks,
    through: :albums,
    source: :tracks

  validates :name, presence: true

  def new
    render :new
  end

  def create
    band = Band.new(band_params)

    if band.save
      redirect_to bands_url
    else
      render :new
    end
  end



  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album

  validates_presence_of :album_id, :title, :track_type
  
end

app/models/user.rb
require 'securerandom'

class User < ActiveRecord::Base
  attr_reader :password
  after_initialize :ensure_session_token

  validates :session_token, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    # fail
    self.password_digest = BCrypt::Password.create(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token
    self.session_token = User.generate_session_token
    self.save!
    # self.class.generate_session_token
    self.session_token
  end

  private
  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end


  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = Album.first
    render :show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def login(user)
    session[:session_token] = user.reset_session_token
  end

  def logout
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def current_user
    user = User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    if current_user
      flash[:error] = "You are already logged in"
      redirect_to user_url(current_user)
    else
      false
    end
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def show
    @band = Band.first
    # fail
    render :show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(params[:session][:email], params[:session][:password])
    # fail
    if user.nil?
      redirect_to new_session_url
    else
      login(user)
      redirect_to user_url(user)
    end
  end

  def new
    render :new
  end

  def destroy
    # fail
    logout
    flash[:error] = "You're now signed out. Thanks, and come back soon!"
    redirect_to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def show
    @track = Track.first
    # fail
    render :show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to users_url
    else
      render :new
    end
  end

  def index
    render :index
  end

  def new
    render :new
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/show.html.erb
<h1><%= @album.name %> by <%= @album.band.name %> </h1>

Track List:
<ul>
<% @album.tracks.each do |track| %>
<li><%= link_to "#{track.title}", track_url(track) %></li>
<% end %>
</ul>

<br><br>

<%= button_to "Edit album", edit_album_url(@album.id), method: "get"  %>
<br>
<%= button_to "Delete album", ("/albums/#{@album.id}"), method: "delete"  %>
<br>
<%= button_to "View this artist's page", ("/bands/#{@album.band_id}"), method: "get" %>

app/views/bands/new.html.erb
<h1>Create a new band</h1>

<form  action="index.html" method="post">

</form>

app/views/bands/show.html.erb
<h1><%= @band.name %> </h1>

Album List:
<ul>
<% @band.albums.each do |album| %>
<li><%= link_to "#{album.name}", album_url(album) %></li>
<br>
<% end %>
</ul>

<br>

<%= button_to "Edit band", edit_band_url(@band.id), method: "get"  %>
<br>
<%= button_to "Delete band", ("/bands/#{@band.id}"), method: "delete"  %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <p color="red"><%= flash[:error] %></p>
    <% if current_user %>
    <form action="/session" method="post">
      <input type="hidden" name="authenticity_token" value="form_authenticity_token">
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="Sign out">
    </form>
    <% end %>
  </header>

<%= yield %>

</body>
</html>

app/views/tracks/show.html.erb
<h1><%= @track.title %> by <%= @track.album.band.name %>  </h1>

Lyrics:
<p><i> <%= @track.lyrics %> </i></p>

<%= button_to "Edit track", edit_track_url(@track.id), method: "get"  %>
<br>
<%= button_to "Delete track", ("/tracks/#{@track.id}"), method: "delete"  %>
<br>
<%= button_to "View the entire album", ("/albums/#{@track.album_id}"), method: "get" %>

app/views/users/index.html.erb
<h1>Welcome to the users homepage!</h1>

app/views/users/new.html.erb
<h1>Sign up as a new free user at MusicApp.com</h1>
<h3>Limited time offer... sign up for a 50 year premium membership subscription and receive 1.5% off!</h3>
<h5>Just use offer code TIL-I-DIE at checkout</h5>

<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <label for="user_email">Email Address</label>
  <input type="text" name="user[email]" id="user_email">

  <br><br>

  <label for="user_password">Password</label>
  <input type="password" name="user[password]" id="user_password">

  <br><br>

  <input type="submit" value="Submit!">

  <br><br>

</form>

app/views/users/show.html.erb
<h1><%= current_user.email %></h1>